// Detect  spam function
const spamPhrases = [
"ganhe dinheiro","cassino","fortuneTiger","oferta limitada","trabalhe de casa","compre agora","milagre","renda extra","sem risco","tente grátis","clicar aqui","aumente seu crédito","garantia de devolução","100% grátis","lucro garantido","pague nada","sem custo","parabéns!","promoção especial","crédito fácil","risco zero","desconto exclusivo","bônus grátis","dinheiro fácil","encaminhe para seus amigos","sem taxas","aproveite a oferta","empréstimo aprovado","poucas unidades","aumente seu limite","novo produto","clique e ganhe","leia agora","mude sua vida","veja como","sucesso imediato","seu nome foi selecionado","reserva garantida","transfira agora","nunca mais sofra","solução instantânea","sem compromisso","resultados rápidos","confidencial","acesso ilimitado","compra urgente","última chance","não perca","crédito liberado","livre-se das dívidas","dívida perdoada","preço mais baixo","aumente sua pontuação","sua sorte chegou","ganhe prêmios","cadastre-se agora","sem compromisso","quebra de sigilo","alerta importante","oferta relâmpago","confira agora","aviso urgente","você ganhou!","participe agora","grátis por tempo limitado","presente especial","recompensa garantida","cheque presente","oferta imperdível","seu dinheiro de volta","recuperação de senha","não compartilhe","detalhes confidenciais","aumento de seguidores","curtidas grátis","pacote de curtidas","ganhe seguidores","comprar curtidas","segredo revelado","atualize sua conta","premiação confirmada","oferta secreta","mais fácil do que você pensa","dinheiro garantido","alerta de segurança","aviso de violação","oportunidade única","seu código de verificação","receba instantaneamente","resgate seu prêmio","última oferta","ação necessária","não perca essa","pode confiar","assine e ganhe","pagamento pendente","transação falhou","limite de crédito","confirmação de pagamento","novos seguidores","aumente sua visibilidade","trabalhe menos, ganhe mais","concurso de prêmios","resultado garantido","aprovação imediata","saia das dívidas","ganho rápido"
];

function detectSpam(emailData) {
    emailData.spam = spamPhrases.some(phrase => emailData.body.toLowerCase().includes(phrase.toLowerCase()) || emailData.subject.toLowerCase().includes(phrase.toLowerCase()));
}

export { detectSpam }